project/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session,g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from .. import db
from ..forms import UserCreateForm, UserLoginForm
from ..models import User

import functools
from datetime import datetime
bp = Blueprint('auth',__name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET','POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data, 
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data,
                        gender=form.gender.data,
                        region=form.region.data,
                        age=form.age.data,
                        create_date=datetime.now()
                        )
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET','POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = '존재하지 않는 사용자 입니다.'
        elif not check_password_hash(user.password, form.password.data):
            error = '비밀번호가 올바르지 않습니다.'
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next','')
            if _next :
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html',form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

project/views/main_views.py
from flask import Blueprint, url_for,render_template
from werkzeug.utils import redirect

bp = Blueprint('main',__name__, url_prefix='/')


@bp.route('/hello')
def hello_pybo():
    return 'Hello, Pybo ~.~'


@bp.route('/', methods=['POST','GET'])
def index():
    return render_template('cp_main.html')

@bp.route('/main/')
def main():
    return redirect(url_for('fridge._list'))

@bp.route('/statistics/')
def statistics():
    return render_template('fridge/cp_statistics.html')

project/views/question_views.py
from datetime import datetime
from urllib.response import addinfo

from flask import Blueprint, render_template, request, url_for, g, flash, Response
from werkzeug.utils import redirect

from .. import db
from ..forms import AddIngredientForm 
from ..models import Ingredient, Recipe_situation, User, Fridge, Recipes, Situation, Recipe_ingredient
from ..views.auth_views import login_required

import cv2
import pyzbar.pyzbar as pyzbar


bp = Blueprint('fridge', __name__, url_prefix='/fridge')
camera = cv2.VideoCapture(0)

@bp.route('/list/', methods=['GET','POST'])
@login_required
def _list():
    if request.method == 'GET':
        page = request.args.get('page', type=int, default=1)
        kw = request.args.get('kw', type=str, default='')
        ingredient_list = Fridge.query.filter(g.user==Fridge.user).order_by(Fridge.exp_date.asc())
        if kw:
            search = '%%{}%%'.format(kw)
            sub_query = db.session.query(Fridge.id, Fridge.product, Fridge.subclass, User.username) \
                .join(User, Fridge.user_id == User.id).subquery()
            ingredient_list = ingredient_list \
                .join(User) \
                .outerjoin(sub_query, sub_query.c.id == Fridge.id) \
                .filter(Fridge.product.ilike(search) |  # 재료
                        Fridge.subclass.ilike(search) |  # 소분류
                        User.username.ilike(search) |  # 질문작성자
                        sub_query.c.username.ilike(search)  # 답변작성자
                        ) \
                .distinct()
        ingredient_list = ingredient_list.paginate(page, per_page=10)
        return render_template('fridge/ingredient_list.html', ingredient_list=ingredient_list, page=page, kw=kw)
    return render_template('cp_main.html')
import psycopg2

def dbconn():
    host = 'jelani.db.elephantsql.com'
    user = 'gycmqpcx'
    password = 'JFjJrpR7BlY0WMoLKw8BsKSCAoFyWBcQ'
    database = 'gycmqpcx'

    conn = psycopg2.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )
    cur = conn.cursor()
    return conn, cur

@bp.route('/recipe/')
def recipe():
    conn,cur = dbconn()
    searches = None
    if request.method == 'GET':
        page = request.args.get('page', type=int, default=1)
        kw = request.args.get('kw', type=str, default='')
        recipe_list = Recipes.query.order_by(Recipes.recommand.desc())
        if kw:
            cur.execute(f"""
            select a.recipe_id, a.recipe_name, a.recipe_desc, a.views, a.recommand, a.scrap, a.cooking_serving, a.level, a.cooking_time
                ,string_agg(c.ingredient_name, ',') as ingredients
            FROM recipes a 
                join recipe_ingredient b on a.recipe_id=b.recipe_id
                join ingredient c on b.ingredient_id = c.ingredient_id
            group by a.recipe_id, a.recipe_name, a.recipe_desc, a.views, a.recommand, a.scrap, a.cooking_serving, a.level, a.cooking_time
            having 
                a.recipe_name like '%{kw}%'
                or string_agg(c.ingredient_name, ',') like '%{kw}%'
            order by 1;
            """)
            searches = cur.fetchall()
        recipe_list = recipe_list.paginate(page, per_page=10)
        conn.close()
        return render_template('fridge/cp_recipe.html', recipe_list=recipe_list, page=page, kw=kw, searches=searches)
    conn.close()
    return render_template('cp_main.html')



@bp.route('/recipe/recommend/')
def recipe_recom():
    if request.method == 'GET':
        page = request.args.get('page', type=int, default=1)
        kw = request.args.get('kw', type=str, default='')
        recipe_list = Recipes.query.order_by(Recipes.recommand.desc())
        if kw:
            search = '%%{}%%'.format(kw)
            db.session.query(Recipes, Recipe_situation, Situation, Recipe_ingredient,Ingredient)\
                .join(Recipe_ingredient, Recipes.recipe_id == Recipe_ingredient.ingredient_id)\
                .join(Ingredient, Recipe_ingredient.ingredient_id == Ingredient.ingredient_id)\
                .join(Recipe_situation, Recipes.recipe_id == Recipe_situation.recipe_id)\
                .join(Situation, Recipe_situation.situation_id == Situation.situation_id)
            recipe_list = recipe_list\
                .filter(Recipes.recipe_desc.ilike(search) |  # 재료
                        Recipes.recipe_name.ilike(search) |  # 소분류
                        Situation.situation_name.ilike(search) |  # 질문작성자
                        Ingredient.ingredient_name.ilike(search)  # 답변작성자
                        ) \
                .distinct()
        recipe_list = recipe_list.paginate(page, per_page=10)
        return render_template('fridge/cp_recipe_recom.html', recipe_list=recipe_list, page=page, kw=kw)
    return render_template('cp_main.html')


@bp.route('/detail/<int:fridge_id>/')
def detail(fridge_id):
    fridge = Fridge.query.get_or_404(fridge_id)
    return render_template('fridge/ingredient_detail.html', fridge=fridge)

@bp.route('/recipe/detail/<int:recipe_id>/')
def recipe_detail(recipe_id):
    conn,cur = dbconn()
    recipe = Recipes.query.get_or_404(recipe_id)
    cur.execute(f"""
select a.recipe_id, a.recipe_name, a.recipe_desc, e.situation_name ,a.views, a.recommand, a.scrap, a.cooking_serving, a.level, a.cooking_time
    ,string_agg(c.ingredient_name, ',') as ingredients
FROM recipes a 
    join recipe_ingredient b on a.recipe_id=b.recipe_id
    join ingredient c on b.ingredient_id = c.ingredient_id
    join recipe_situation d on a.recipe_id = d.recipe_id 
    join situation e on d.situation_id = e.situation_id 
group by a.recipe_id, a.recipe_name, e.situation_name, a.recipe_desc, a.views, a.recommand, a.scrap, a.cooking_serving, a.level, a.cooking_time
having a.recipe_id = {recipe_id};
""")
    r_detail = cur.fetchone()
    conn.close()
    return render_template('fridge/recipe_detail.html', recipe=recipe, r_detail=r_detail)


@bp.route('/add_ingredient/', methods=['GET','POST'])
@login_required
def create():
    form = AddIngredientForm()
    if request.method == 'POST' and form.validate_on_submit():
        fridge = Fridge(barcode = form.barcode.data,
                        product=form.product.data, 
                        subclass=form.subclass.data,
                        qty=form.qty.data,
                        exp_date=form.exp_date.data,
                        adding_date = form.adding_date.data,
                        user=g.user)
        db.session.add(fridge)
        db.session.commit()
        return redirect(url_for('main.main'))
    return render_template('fridge/cp_add.html', form=form)

@bp.route('/modify/<int:fridge_id>', methods=('GET','POST'))
@login_required
def modify(fridge_id):
    fridge = Fridge.query.get_or_404(fridge_id)
    if g.user != fridge.user:
        flash('수정권한이 없습니다.')
        return redirect(url_for('fridge.detail', fridge_id=fridge_id))
    if request.method == 'POST':
        form = AddIngredientForm()
        if form.validate_on_submit():
            form.populate_obj(fridge)
            fridge.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('fridge.detail', fridge_id=fridge_id))
    else:
        form = AddIngredientForm(obj=fridge)
    return render_template('fridge/cp_add.html', form=form)

@bp.route('/delete/<int:fridge_id>')
@login_required
def delete(fridge_id):
    fridge = Fridge.query.get_or_404(fridge_id)
    if g.user != fridge.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('fridge.detail', fridge_id=fridge_id))
    db.session.delete(fridge)
    db.session.commit()
    return redirect(url_for('fridge._list'))
    
def gen_frames():  # generate frame by frame from camera
    while True:
        # Capture frame-by-frame
        success, frame = camera.read()  # read the camera frame
        if not success:
            break
        else:
            for code in pyzbar.decode(frame):
                cv2.imwrite('barcode_image.png', frame)
                my_code = code.data.decode('utf-8')
                print("바코드 : ", my_code)

            ret, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')  # concat frame one by one and show result

@bp.route('/video_feed/')
def video_feed():
    #Video streaming route. Put this in the src attribute of an img tag
    return Response(gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')


@bp.route('/barcode/')
def index_barcode():
    """Video streaming home page."""
    return render_template('fridge/index.html')

project/templates/cp_main.html
{%extends 'practice.html'%}
{%block content%}
<section id="main" class="hero d-flex align-items-center section-bg">
  <div class="container">
    <div class="row justify-content-between gy-5">
      <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center align-items-center align-items-lg-start text-center text-lg-start">
        <h3 id="main_text" data-aos="fade-up" class="aos-init aos-animate">2023년 1월 1일부터<br> 유통기한 표기법이<br> 소비기한으로 바뀝니다.<br>
          <p id="main_text_ex" data-aos="fade-up" data-aos-delay="100" class="aos-init aos-animate">✔ 소비기한 : 표시된 조건에서 보관하면 소비해도 안전에 이상이 없는 기간</p></h3><br>
        
        <p id="sub_text" data-aos="fade-up" data-aos-delay="100" class="aos-init aos-animate">- 바코드 촬영으로 간편하게 식재료 등록
        <p id="sub_text" data-aos="fade-up" data-aos-delay="100" class="aos-init aos-animate">- 유통기한이 짧은 식재료의 유통기한을 관리
        <p id="sub_text" data-aos="fade-up" data-aos-delay="100" class="aos-init aos-animate">- 키워드 추출을 이용한 레시피 추천
        </p></p>  
      </div>
      <div class="col-lg-5 order-1 order-lg-2 text-center text-lg-start">
        <img src="{{url_for('static', filename='img/hero-img.png')}}" class="img-fluid aos-init aos-animate" alt="" data-aos="zoom-out" data-aos-delay="300">
      </div>
    </div>
  </div>
</section>
  {% endblock %}

project/templates/form_errors.html
<!-- 필드 오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>
        {{ form[field].label }}
    </strong>: {{', '.join(errors) }}
</div>
{% endfor %}
<!-- 플래시 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

project/templates/practice.html
<html lang="en"><head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>소비기한 언제지</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{url_for('static', filename='img/favicon.png')}}" rel="icon">
  <link href="{{url_for('static', filename='img/apple-touch-icon.png')}}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&amp;family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&amp;family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&amp;display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/aos/aos.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Yummy - v1.1.0
  * Template URL: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body data-aos-easing="ease-in-out" data-aos-duration="1000" data-aos-delay="0">

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center sticked">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="{{ url_for('main.index') }}" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="static/img/logo.png" alt=""> -->
        <h1>소비기한 언제지<span>.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        
        <ul>
          <li><a href="{{ url_for('main.index') }}" class="">메인</a></li>
          <li><a href="{{ url_for('main.main') }}" class="">나의냉장고</a></li>
          <li><a href="{{ url_for('fridge.recipe') }}" class="">레시피 목록</a></li>
          <li><a href="{{ url_for('fridge.recipe_recom') }}" class="">레시피 골라보기</a></li>
          <li><a href="{{ url_for('main.statistics') }}" class="">재미있는 통계</a></li>           
        </ul>
      </nav><!-- .navbar -->
      {% if g.user %}
      <div class="align-items-right"></div>
        <a href="{{ url_for('fridge.create') }}" class="btn-book-a-table">냉장고 채우기</a>
        <a href="{{ url_for('auth.logout') }}" class="btn-book-a-table">{{ g.user.username }} 로그아웃</a>

        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
      </div>
      {% else %}
      <div class="align-items-right"></div>
      <a href="{{ url_for('fridge.create') }}" class="btn-book-a-table">냉장고 채우기</a>
      <a href="{{ url_for('auth.login') }}" class="btn-book-a-table">로그인</a>
      <a href="{{ url_for('auth.signup') }}" class="btn-book-a-table">회원가입</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
    </div>
    {% endif %}
  </header><!-- End Header -->

  <!-- ======= 메인 Section ======= -->

  <!-- ======= End 메인 Section ======= -->

  <main id="main">

    <!-- ======= 나의 냉장고 Section ======= -->
    {%block content%}
    {%endblock%}
    <!-- ======= End 나의 냉장고 Section ======= -->

    <!-- ======= 어플을 사용해야되는 이유? Section ======= -->
   
    <!-- ======= End 어플을 사용해야되는 이유? Section ======= -->
<!-- ======= 제품등록 Section ======= -->

<!-- ======= End 제품등록 Section ======= -->
    <!-- ======= 레시피 Section ======= -->
   
    <!-- ======= End 레시피 Section ======= -->

    <!-- ======= 통계 Section ======= -->
    
    <!-- ======= End 통계 Section ======= -->

   


  </main><!-- End #main -->

  <!-- ======= 맨 아래 바 ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-2 col-md-6 d-flex">
          <div>
            <h4>YOONSIK CHOO</h4>
            <p>
              Github <br>
              <a href='https://github.com/ChooYoonSik'>https://github.com/ChooYoonSik</a><br>
            </p>
          </div>
        </div>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <div class="col-lg-2 col-md-6 d-flex">
          <div>
            <h4>HYEJI KWAK</h4>
            <p>
              Github <br>
              <a href='https://github.com/kkwakkwaks'>https://github.com/kkwakkwaks</a><br>
            </p>
          </div>
        </div>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <div class="col-lg-2 col-md-6 d-flex">
          <div>
            <h4>KIDON LEE</h4>
            <p>
              Github <br>
              <a href='https://github.com/GitPolyMath'>https://github.com/GitPolyMath</a><br>
            </p>
          </div>
        </div>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <div class="col-lg-2 col-md-6 d-flex">
          <div>
            <h4>HEESUN PARK</h4>
            <p>
              Github <br>
              <a href='https://github.com/heesunpark1'>https://github.com/heesunpark1</a><br>
            </p>
          </div>
        </div>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <div class="col-lg-2 col-md-6 d-flex">
          <div>
            <h4>JOOYEON ROH</h4>
            <p>
              Github <br>
              <a href=https://github.com/jooyeonroh>https://github.com/jooyeonroh</a><br>
            </p>
          </div>
        </div>
          <!-- <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Reservations</h4>
            <p>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat: 11AM</strong> - 23PM<br>
              Sunday: Closed
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div> -->
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        © Copyright <strong><span>Yummy</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer>
  <!-- End 맨 아래 바 -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center active"><i class="bi bi-arrow-up-short"></i></a>


  <!-- Vendor JS Files -->
  <script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{url_for('static', filename='vendor/aos/aos.js')}}"></script>
  <script src="{{url_for('static', filename='vendor/glightbox/js/glightbox.min.js')}}"></script>
  <script src="{{url_for('static', filename='vendor/purecounter/purecounter_vanilla.js')}}"></script>
  <script src="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.js')}}"></script>


  <!-- Template Main JS File -->
  <script src="{{url_for('static', filename='js/main.js')}}"></script>

  <link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css" />
  <script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>
  <script src="{{url_for('static', filename='js/grid.js')}}"></script>

  
  {% block script %}
  {% endblock %}

</body></html>