project/views/question_views.py
from datetime import datetime
from urllib.response import addinfo

from flask import Blueprint, render_template, request, url_for, g, flash, Response
from werkzeug.utils import redirect

from .. import db
from ..forms import AddIngredientForm 
from ..models import Ingredient, Recipe_situation, User, Fridge, Recipes, Situation, Recipe_ingredient
from ..views.auth_views import login_required

import cv2
import pyzbar.pyzbar as pyzbar


bp = Blueprint('fridge', __name__, url_prefix='/fridge')
camera = cv2.VideoCapture(0)

@bp.route('/list/', methods=['GET','POST'])
@login_required
def _list():
    if request.method == 'GET':
        page = request.args.get('page', type=int, default=1)
        kw = request.args.get('kw', type=str, default='')
        ingredient_list = Fridge.query.filter(g.user==Fridge.user).order_by(Fridge.exp_date.asc())
        if kw:
            search = '%%{}%%'.format(kw)
            sub_query = db.session.query(Fridge.id, Fridge.product, Fridge.subclass, User.username) \
                .join(User, Fridge.user_id == User.id).subquery()
            ingredient_list = ingredient_list \
                .join(User) \
                .outerjoin(sub_query, sub_query.c.id == Fridge.id) \
                .filter(Fridge.product.ilike(search) |  # 재료
                        Fridge.subclass.ilike(search) |  # 소분류
                        User.username.ilike(search) |  # 질문작성자
                        sub_query.c.username.ilike(search)  # 답변작성자
                        ) \
                .distinct()
        ingredient_list = ingredient_list.paginate(page, per_page=10)
        return render_template('fridge/ingredient_list.html', ingredient_list=ingredient_list, page=page, kw=kw)
    return render_template('cp_main.html')
import psycopg2

def dbconn():
    host = 'jelani.db.elephantsql.com'
    user = 'gycmqpcx'
    password = 'JFjJrpR7BlY0WMoLKw8BsKSCAoFyWBcQ'
    database = 'gycmqpcx'

    conn = psycopg2.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )
    cur = conn.cursor()
    return conn, cur

@bp.route('/recipe/')
def recipe():
    conn,cur = dbconn()
    searches = None
    if request.method == 'GET':
        page = request.args.get('page', type=int, default=1)
        kw = request.args.get('kw', type=str, default='')
        recipe_list = Recipes.query.order_by(Recipes.recommand.desc())
        if kw:
            cur.execute(f"""
            select a.recipe_id, a.recipe_name, a.recipe_desc, a.views, a.recommand, a.scrap, a.cooking_serving, a.level, a.cooking_time
                ,string_agg(c.ingredient_name, ',') as ingredients
            FROM recipes a 
                join recipe_ingredient b on a.recipe_id=b.recipe_id
                join ingredient c on b.ingredient_id = c.ingredient_id
            group by a.recipe_id, a.recipe_name, a.recipe_desc, a.views, a.recommand, a.scrap, a.cooking_serving, a.level, a.cooking_time
            having 
                a.recipe_name like '%{kw}%'
                or string_agg(c.ingredient_name, ',') like '%{kw}%'
            order by 1;
            """)
            searches = cur.fetchall()
        recipe_list = recipe_list.paginate(page, per_page=10)
        conn.close()
        return render_template('fridge/cp_recipe.html', recipe_list=recipe_list, page=page, kw=kw, searches=searches)
    conn.close()
    return render_template('cp_main.html')



@bp.route('/recipe/recommend/')
def recipe_recom():
    if request.method == 'GET':
        page = request.args.get('page', type=int, default=1)
        kw = request.args.get('kw', type=str, default='')
        recipe_list = Recipes.query.order_by(Recipes.recommand.desc())
        if kw:
            search = '%%{}%%'.format(kw)
            db.session.query(Recipes, Recipe_situation, Situation, Recipe_ingredient,Ingredient)\
                .join(Recipe_ingredient, Recipes.recipe_id == Recipe_ingredient.ingredient_id)\
                .join(Ingredient, Recipe_ingredient.ingredient_id == Ingredient.ingredient_id)\
                .join(Recipe_situation, Recipes.recipe_id == Recipe_situation.recipe_id)\
                .join(Situation, Recipe_situation.situation_id == Situation.situation_id)
            recipe_list = recipe_list\
                .filter(Recipes.recipe_desc.ilike(search) |  # 재료
                        Recipes.recipe_name.ilike(search) |  # 소분류
                        Situation.situation_name.ilike(search) |  # 질문작성자
                        Ingredient.ingredient_name.ilike(search)  # 답변작성자
                        ) \
                .distinct()
        recipe_list = recipe_list.paginate(page, per_page=10)
        return render_template('fridge/cp_recipe_recom.html', recipe_list=recipe_list, page=page, kw=kw)
    return render_template('cp_main.html')


@bp.route('/detail/<int:fridge_id>/')
def detail(fridge_id):
    fridge = Fridge.query.get_or_404(fridge_id)
    return render_template('fridge/ingredient_detail.html', fridge=fridge)

@bp.route('/recipe/detail/<int:recipe_id>/')
def recipe_detail(recipe_id):
    conn,cur = dbconn()
    recipe = Recipes.query.get_or_404(recipe_id)
    cur.execute(f"""
select a.recipe_id, a.recipe_name, a.recipe_desc, e.situation_name ,a.views, a.recommand, a.scrap, a.cooking_serving, a.level, a.cooking_time
    ,string_agg(c.ingredient_name, ',') as ingredients
FROM recipes a 
    join recipe_ingredient b on a.recipe_id=b.recipe_id
    join ingredient c on b.ingredient_id = c.ingredient_id
    join recipe_situation d on a.recipe_id = d.recipe_id 
    join situation e on d.situation_id = e.situation_id 
group by a.recipe_id, a.recipe_name, e.situation_name, a.recipe_desc, a.views, a.recommand, a.scrap, a.cooking_serving, a.level, a.cooking_time
having a.recipe_id = {recipe_id};
""")
    r_detail = cur.fetchone()
    conn.close()
    return render_template('fridge/recipe_detail.html', recipe=recipe, r_detail=r_detail)


@bp.route('/add_ingredient/', methods=['GET','POST'])
@login_required
def create():
    form = AddIngredientForm()
    if request.method == 'POST' and form.validate_on_submit():
        fridge = Fridge(barcode = form.barcode.data,
                        product=form.product.data, 
                        subclass=form.subclass.data,
                        qty=form.qty.data,
                        exp_date=form.exp_date.data,
                        adding_date = form.adding_date.data,
                        user=g.user)
        db.session.add(fridge)
        db.session.commit()
        return redirect(url_for('main.main'))
    return render_template('fridge/cp_add.html', form=form)

@bp.route('/modify/<int:fridge_id>', methods=('GET','POST'))
@login_required
def modify(fridge_id):
    fridge = Fridge.query.get_or_404(fridge_id)
    if g.user != fridge.user:
        flash('수정권한이 없습니다.')
        return redirect(url_for('fridge.detail', fridge_id=fridge_id))
    if request.method == 'POST':
        form = AddIngredientForm()
        if form.validate_on_submit():
            form.populate_obj(fridge)
            fridge.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('fridge.detail', fridge_id=fridge_id))
    else:
        form = AddIngredientForm(obj=fridge)
    return render_template('fridge/cp_add.html', form=form)

@bp.route('/delete/<int:fridge_id>')
@login_required
def delete(fridge_id):
    fridge = Fridge.query.get_or_404(fridge_id)
    if g.user != fridge.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('fridge.detail', fridge_id=fridge_id))
    db.session.delete(fridge)
    db.session.commit()
    return redirect(url_for('fridge._list'))
    
def gen_frames():  # generate frame by frame from camera
    while True:
        # Capture frame-by-frame
        success, frame = camera.read()  # read the camera frame
        if not success:
            break
        else:
            for code in pyzbar.decode(frame):
                cv2.imwrite('barcode_image.png', frame)
                my_code = code.data.decode('utf-8')
                print("바코드 : ", my_code)

            ret, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')  # concat frame one by one and show result

@bp.route('/video_feed/')
def video_feed():
    #Video streaming route. Put this in the src attribute of an img tag
    return Response(gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')


@bp.route('/barcode/')
def index_barcode():
    """Video streaming home page."""
    return render_template('fridge/index.html')

project/templates/fridge/cp_add.html
{%extends 'practice.html'%}
{%block content%}
 <section id="add_ingredient" class="book-a-table">
    <div class="container aos-init aos-animate" data-aos="fade-up">
  
      <div class="section-header">
        <br>
        <h2>재료추가</h2>
        <p>재료 <span>추가</span></p>
      </div>
  
      <div class="row g-0">
        <div class="col-6">
          <a href="{{ url_for('fridge.index_barcode') }}" class="btn btn-primary">바코드 촬영</a>
      </div>
        <div class="col-lg-4 reservation-img aos-init aos-animate" style="background-image: url(static/img/reservation.jpg);" data-aos="zoom-out" data-aos-delay="200"></div>
  
        <div class="col-lg-8 d-flex align-items-center reservation-form-bg">
         
          <form method="post" role="form" class="php-email-form aos-init aos-animate" data-aos="fade-up" data-aos-delay="100">
            {{form.csrf_token }}
            <!-- 오류표시 -->
            {% for field, errors in form.errors.items() %}
            <div class="alert alert-danger" role="alert">
                <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
            </div>
            {% endfor %}
            <!-- 오류표시 끝 -->
        <!-- 오류표시 End -->
            <div class="row gy-4">
              <div class="col-lg-4 col-md-6">
                <input type="text" class="form-control" name="barcode" id="barcode" placeholder="바코드" 
                value="{{ form.barcode.data or '' }}">
                <div class="validate"></div>
              </div>
              <div class="col-lg-4 col-md-6">
                <input type="text" class="form-control" name="product" id="product" placeholder="제품명" 
                value="{{ form.product.data or '' }}">
                <div class="validate"></div>
              </div>
              <div class="col-lg-4 col-md-6">
                <select type="text" class="form-control" name="subclass" id="subclass" placeholder="소분류">
                <!-- value="{{ form.subclass.data or '' }}"> -->
                <option style="color:lightgrey" value="none">소분류</option>
                <option value="김치">김치</option>
                <option value="닭고기">닭고기</option>
                <option value="돼지고기">돼지고기</option>
                <option value="두부">두부</option>
                <option value="묵">묵</option>
                <option value="베이컨">베이컨</option>
                <option value="소시지">소시지</option>
                <option value="어묵">어묵</option>
                <option value="우유">우유</option>
                <option value="육류">육류</option>
                <option value="치즈">치즈</option>
                <option value="햄">햄</option>
                <option value="기타">기타</option>
               </select>
                <div class="validate"></div>
              </div>
              <div class="col-lg-4 col-md-6">
                <input type="number" class="form-control" name="qty" id="qty" placeholder="수량" 
                value="{{ form.qty.data or '' }}">
                <div class="validate"></div>
              </div>
              <div class="col-lg-4 col-md-6">유통기한/소비기한
                <input type="date" class="form-control" name="exp_date" id="exp_date" placeholder="유통기한" 
                value="{{ form.exp_date.data or '' }}">
                <div class="validate"></div>
              </div>
              <div class="col-lg-4 col-md-6">추가한 날짜
                <input type="date" class="form-control" name="adding_date" id="adding_date" placeholder="추가한 날짜"
                value="{{ form.adding_date.data or '' }}">
                <div class="validate"></div>
              </div>
            </div>
            
            <div class="mb-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your booking request was sent. We will call back or send an Email to confirm your reservation. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit">선택 완료</button></div>
          </form>
        </div><!-- End Reservation Form -->
  
      </div>
  
    </div>
  </section>
  {% endblock %}

project/templates/fridge/cp_fridge.html
{%extends 'practice.html'%}
{%block content%}
<section id="my_fridge" class="about">
    <div class="container aos-init aos-animate" data-aos="fade-up">

      <div class="section-header">
        <br>
        <h2>My Refrigerator</h2>
        <p>냉장고를 <span>부탁해</span></p>
      </div>

      <div id="grid"></div>

    </div>


  <div class="container aos-init aos-animate" data-aos="fade-up">
    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ fridge.product }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ fridge.qty }}</div>
            <div class="d-flex justify-content-end">
                {% if fridge.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ fridge.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ fridge.user.username }}</div>
                    <div>{{ fridge.create_date|datetime }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if g.user == fridge.user %}
                <a href="{{ url_for('fridge.modify', question_id=question.id) }}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{ url_for('fridge.delete', question_id=quesiton.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>

</div>
</section>
{%endblock%}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
  {% endblock %}

project/templates/fridge/cp_recipe.html
{% extends 'practice.html' %}
{% block content %}
<div class="container my-3">
    <br>
    <br><br>
    <br>
    <div class="row my-3">
        <div class="col-6">
          <h2>레시피 목록</h2>
          <p>입력한 재료로 만들 수 있는 레시피 목록</p> 

        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}" placeholder="찾고싶은 요리명 혹은 재료명을 입력해주세요" >
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search" >찾기</button>
                </div>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th style="width:50%">요리명</th>
            <th>추천수(▼)</th>
            <th>요리 시간</th>
            <th>요리 난이도</th>
            <th>조회수</th>
        </tr>
        </thead>
        <tbody>
        {% if searches %}
        {% for search in searches %}
        <tr class="text-center">
            <td class="text-start" style="border: 2px;">
                <a href="{{ url_for('fridge.recipe_detail', recipe_id=search[0] ) }}" style="border: 2px;">{{ search[1] }}</a>
            </td>
            <td>{{ search[4] }}</td>
            <td>{{ search[8] }}</td>
            <td>{{ search[7] }}</td>
            <td>{{ search[3] }}</td>
        </tr>
        {% endfor %}
        {% elif recipe_list %}
        {% for recipe in recipe_list.items %}
        <tr class="text-center">
            <td class="text-start">
                <a href="{{ url_for('fridge.recipe_detail', recipe_id=recipe.recipe_id) }}">{{ recipe.recipe_name }}</a>
            </td>
            <td>{{ recipe.recommand }}</td>
            <td>{{ recipe.cooking_time }}</td>
            <td>{{ recipe.level}}</td>
            <td>{{ recipe.views}}</td>
        </tr>
        {% endfor %}
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if recipe_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ recipe_list.prev_num }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" data-page="{{ recipe_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in recipe_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != recipe_list.page %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if recipe_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ recipe_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <section id="recipe" class="menu">
        
      <div class="container aos-init aos-animate" data-aos="fade-up">
  
        <div class="section-header">
          <br>
         
    </div>
    </section>
  
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{{ url_for('fridge.recipe') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

 

project/templates/fridge/cp_recipe_recom.html
{% extends 'practice.html' %}
{% block content %}
<div class="container my-3">
    
    <section id="recipe" class="menu">
        
      <div class="container aos-init aos-animate" data-aos="fade-up">
  
        <div class="section-header">
          <br>
          <h2>RECIPE</h2>
          <p>레시피 골라보기</p>
        </div>
        
        <div class='tableauPlaceholder' id='viz1662963821085' style='position: relative'>
          <noscript>
            <a href='#'>
              <img alt='대시보드 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;cp&#47;cp1_16629199446500&#47;1&#47;1_rss.png' style='border: none' />
            </a>
          </noscript>
          <object class='tableauViz'  style='display:none;'>
            <param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> 
            <param name='embed_code_version' value='3' /> 
            <param name='site_root' value='' />
            <param name='name' value='cp1_16629199446500&#47;1' />
            <param name='tabs' value='no' /><param name='toolbar' value='yes' />
            <param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;cp&#47;cp1_16629199446500&#47;1&#47;1.png' /> 
            <param name='animate_transition' value='yes' />
            <param name='display_static_image' value='yes' />
            <param name='display_spinner' value='yes' />
            <param name='display_overlay' value='yes' />
            <param name='display_count' value='yes' />
            <param name='language' value='ko-KR' />
            <param name='filter' value='publish=yes' />
          </object>
        </div>                
        <script type='text/javascript'>                    
          var divElement = document.getElementById('viz1662963821085');                    
          var vizElement = divElement.getElementsByTagName('object')[0];                    
          if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1200px';vizElement.style.height='827px';} 
          else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1200px';vizElement.style.height='827px';} 
          else { vizElement.style.width='100%';vizElement.style.height='1227px';}                     
          var scriptElement = document.createElement('script');                    
          scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    
          vizElement.parentNode.insertBefore(scriptElement, vizElement);                
        </script>

        <!-- <form action="forms/book-a-table.php" method="post" role="form" class="php-email-form aos-init aos-animate" data-aos="fade-up" data-aos-delay="100">
          <div class="row gy-4">
            
            <div class="col-lg-2 col-md-6">
              요리방법 <select name="name" class="form-control" id="name" value="{{ kw or '' }}">
                <option value="">선택안함</option>
                <option value="볶음">볶음</option>
                <option value="굽기">굽기</option>
                <option value="찜">찜</option>
                <option value="조림">조림</option>
                <option value="부침">부침</option>
                <option value="튀김">튀김</option>
                <option value="무침">무침</option>
                <option value="끓이기">끓이기</option>
                <option value="삶기">삶기</option>
                <option value="데치기">데치기</option>
                <option value="회">회</option>
                <option value="절임">절임</option>
                <option value="비빔">비빔</option>
                <div class="validate"></div>
              </select>
            </div>
            <div class="col-lg-2 col-md-6">
              요리상황 <select name="name" class="form-control" id="name">
                <option value="">선택안함</option>
                <option value="일상">일상</option>
                <option value="손님접대">손님접대</option>
                <option value="술안주">술안주</option>
                <option value="영양식">영양식</option>
                <option value="초스피드">초스피드</option>
                <option value="명절">명절</option>
                <option value="간식">간식</option>
                <option value="다이어트">다이어트</option>
                <option value="야식">야식</option>
                <option value="도시락">도시락</option>
                <option value="해장">해장</option>
                <div class="validate"></div>
              </select>
            </div>
            <div class="col-lg-2 col-md-6">
              난이도 <select name="name" class="form-control" id="name">
                <option value="">선택안함</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <div class="validate"></div>
              </select>
            </div>
            <div class="col-lg-2 col-md-6">
              요리시간(분) <select name="name" class="form-control" id="name">
                <option value="">선택안함</option>
                <option value="5">5</option>
                <option value="10">10</option>
                <option value="15">15</option>
                <option value="30">30</option>
                <option value="60">60</option>
                <option value="90">90</option>
                <option value="120">120</option>
                <div class="validate"></div>
              </select>
            </div>
            <div class="col-lg-3 col-md-6">
              요리 재료 <input class="form-control" name="message"/>
              <div class="validate"></div>
            </div>
            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
          </div>
          <div class="container">
        </form> -->
      </div>
    </section>

    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{{ url_for('fridge.recipe') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

 
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms

project/templates/fridge/index.html
{%extends 'practice.html'%}
{%block content%}

    <title>바코드 등록 페이지</title>
<body>
    <br><br><br><br><br><br><br>
<div class="container">
    <div class="row">
        <div class="col-lg-8  offset-lg-2">
            <h3 class="mt-5"> 바코드를 카메라에 보여주세요.</h3>
            <img src="{{ url_for('fridge.video_feed') }}" width="100%">
            <h3 class="mt-5"> 바코드를 카메라에 갖다대면 자동으로 인식됩니다.</h3>
            <a href="{{ url_for('fridge.create') }}" class="btn btn-primary">등록</a>
                <input type=button value="화면 캡쳐" onclick="{takeSnapshot()}"><br>

        </div>
    </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br>
</body>
{% endblock %}

project/templates/fridge/ingredient_detail.html
{%extends 'practice.html'%}
{%block content%}
<div class="container my-3">
    <br><br>
    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <br><br>
    <h2 class="border-bottom py-2">{{ fridge.product }}</h2>
            <table class="table">
                <thead>
                    <tr class="text-center thead-dark">
                        <th>소분류</th>
                        <th>바코드</th>
                        <th>수량</th>
                        <th>유통기한/소비기한</th>
                        <th>재료 추가 일</th>
                        <th>변경 일자</th>
                    </tr></thead>
                    <tbody>
                        <tr class="text-center">
                            <td>{{ fridge.subclass }}</td>
                            <td>{{ fridge.barcode }}</td>
                            <td>{{ fridge.qty }}</td>
                            <td>{{ fridge.exp_date }}</td>
                            {% if fridge.modify_date %}
                            <td>{{ fridge.modify_date|datetime }}</td>
                            {% endif %}
                            <td>{{ fridge.adding_date|datetime }}</td>
                        </tr>
                    </tbody>
                </thead>

       
                <div class="badge bg-light text-dark p-2 text-start">
                   <div class="mb-2">{{ fridge.user.username }}</div>

        </table>
            <div class="my-3">
                {% if g.user == fridge.user %}
                <a href="{{ url_for('fridge.modify',  fridge_id=fridge.id) }}"
                     class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{{ url_for('fridge.delete', fridge_id=fridge.id) }}">삭제</a>
                {% endif %}
       
            </div>
        </div>
    </div>

</div>
{%endblock%}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}